name: CI/CD Deploy on Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64, techletter-prod]
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stop existing application and Run new version
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL_PROD }}

        run: |
          docker-compose down -f docker-compose.prod.yml
          docker-compose up -d --build -f docker-compose.prod.yml
